[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "phase-studio"
version = "1.0.6"
description = "Qt application for iterative Superflip, SharpED server deblurring and EDMA crystallographic reconstruction."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "matplotlib",
  "gemmi",
]

[project.optional-dependencies]
app = [
  "PySide6",
  "qtvscodestyle",
]
qt = [
  "PySide6",
  "qtvscodestyle",
]
build = [
  "pyinstaller",
]
dev = [
  "PySide6",
  "qtvscodestyle",
  "pyinstaller",
]

[project.scripts]
phase-studio = "phase_studio.app:main"

[tool.setuptools]
packages = ["phase_studio"]

[tool.setuptools.package-data]
phase_studio = ["assets/*.svg", "assets/*.xpm", "assets/*.ico"]
